Repository glass-dev/glass, pull requests merged in 2024-10, with the labels that each got.

#291 gh-290: add extra contact links to the raise issue button
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, enhancement

#284 gh-267: move arguments from `pre-commit` to config files
  .pre-commit-config.yaml
  .prettierrc.yaml
  .yamllint.yaml
  pyproject.toml
Labels: infrastructure

#294 gh-293: remove unused mailing list link in README
  README.md
Labels: bug, documentation

#263 gh-268: add more tests for `glass.core`
  tests/core/test_algorithm.py
  tests/core/test_array.py
Labels: maintenance

#264 gh-276: add tests for `glass.shapes`
  tests/test_shapes.py
Labels: maintenance

#298 gh-297: do not autofix PRs using pre-commit.ci
  .pre-commit-config.yaml
Labels: bug

#287 gh-283: set up nox for developers and CI
  .github/workflows/examples.yml
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  noxfile.py
  pyproject.toml
Labels: infrastructure

#295 gh-292: Add `markdownlint` to list of `pre-commit` hooks
  .pre-commit-config.yaml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement, infrastructure

#301 gh-300: convert tabs to spaces and disable generally
  .pre-commit-config.yaml
  docs/make.bat
Labels: infrastructure

#305 gh-246: replace `numpy.ndarray` with `numpy.typing.NDArray`
  glass/core/algorithm.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/shapes.py
  glass/shells.py
  tests/core/test_array.py
  tests/test_lensing.py
  tests/test_points.py
Labels: maintenance

#310 gh-307: fix nox examples session
  noxfile.py
Labels: bug, infrastructure

#303 gh-302: add `actionlint` and fix issues
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: infrastructure

#316 gh-304: exclude a few things from SDist
  pyproject.toml
Labels: maintenance

#322 gh-321: group markdown badges into sections
  README.md
Labels: documentation, enhancement

#318 gh-282: extend `coverage` options to improve output
  CONTRIBUTING.md
  noxfile.py
  pyproject.toml
Labels: enhancement, infrastructure

#320 gh-319: run coverage in parallel and aggregate results
  .github/workflows/test.yml
Labels: enhancement, infrastructure

#326 gh-198: enforce `python>3.8` & `numpy>1.21`
  .github/workflows/test.yml
  glass/fields.py
  glass/lensing.py
  glass/shells.py
  noxfile.py
  pyproject.toml
  tests/test_fits.py
Labels: infrastructure

#324 gh-323: rm broken support for uv + update constraint format
  .github/test-constraints.txt
  noxfile.py
Labels: bug, maintenance

#331 gh-327: use `numpy.testing` everywhere in existing tests
  tests/core/test_array.py
  tests/test_lensing.py
  tests/test_shapes.py
  tests/test_shells.py
Labels: maintenance

#332 gh-328: fix shape mismatch bug in ellipticity_ryden04
  glass/shapes.py
Labels: bug

#339 gh-338: better autoupdate and autofix messages for pre-commit.ci
  .pre-commit-config.yaml
Labels: maintenance

#333 gh-137: deprecate `redshifts_from_nz` in favor of `redshifts`
  glass/galaxies.py
  tests/test_galaxies.py
Labels: maintenance

#343 gh-342: install libbz2-dev and use setup-python
  .github/workflows/test.yml
Labels: infrastructure

#344 gh-270: add missing tests for glass.galaxies
  tests/test_galaxies.py
Labels: maintenance

#347 gh-346: enforce `NumPy` docstrings + use static typing in docs
  docs/conf.py
  glass/core/__init__.py
  glass/core/algorithm.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
Labels: enhancement, dependencies

#341 gh-328: efficient resampling in `ellipticity_ryden04`
  glass/shapes.py
Labels: performance

#357 gh-352: fix latex rendering
  glass/lensing.py
  glass/points.py
  glass/shells.py
Labels: documentation

#359 gh-280: add `mypy` to codebase
  .pre-commit-config.yaml
  docs/conf.py
  glass/core/array.py
  glass/ext/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
  tests/conftest.py
  tests/core/test_algorithm.py
  tests/core/test_array.py
  tests/test_fields.py
  tests/test_fits.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_points.py
  tests/test_shapes.py
  tests/test_shells.py
Labels: enhancement, maintenance

#360 gh-248: a few fixes for ignored and recommended ruff rules
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/photoz.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  pyproject.toml
  tests/test_galaxies.py
  tests/test_shapes.py
Labels: maintenance

#325 gh-175: add CITATION.cff and bib entry in README
  CITATION.bib
  CITATION.cff
  README.md
Labels: documentation

#345 gh-131: rename `gaussian_gls` to `discretized_cls`
  examples/1-basic/cls.npy
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/__init__.py
  glass/fields.py
Labels: api

#370 gh-161: bump coverage for galaxies and shapes
  tests/test_galaxies.py
  tests/test_shapes.py
Labels: maintenance

#373 Fix `Returns` in docstrings (I think entered in #357)
  glass/observations.py
  glass/points.py
  glass/shapes.py
Labels: bug, documentation

#380 gh-379: fix warnings when running the notebooks
  examples/1-basic/photoz.ipynb
  examples/2-advanced/cosmic_shear.ipynb
Labels: bug, documentation
