Repository glass-dev/glass, pull requests merged in 2024-11, with the labels that each got.

#393 gh-362: review the `ruff-format` recommended rules
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/ext/__init__.py
  glass/fields.py
  glass/lensing.py
  glass/shells.py
  noxfile.py
  pyproject.toml
  tests/test_galaxies.py
Labels: enhancement, maintenance

#388 gh-354: tidy Actions, name steps, cache dependencies
  .github/workflows/examples.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement, infrastructure, performance

#396 gh-342: explicit libbz2-dev installation is not required now
  .github/workflows/test.yml
Labels: maintenance

#368 gh-358: add static types support
  .gitignore
  .pre-commit-config.yaml
  docs/conf.py
  glass/core/algorithm.py
  glass/core/array.py
  glass/ext/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/py.typed
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
  tests/conftest.py
  tests/core/test_algorithm.py
  tests/core/test_array.py
  tests/test_fields.py
  tests/test_fits.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_points.py
  tests/test_shapes.py
  tests/test_shells.py
Labels: enhancement, maintenance, typing

#394 gh-248: fix all remaining possible ruff `# noqa` statements
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  glass/lensing.py
  glass/observations.py
  glass/shapes.py
  glass/shells.py
  pyproject.toml
  tests/test_fits.py
Labels: enhancement, infrastructure

#337 gh-336: support Python 3.13
  .github/workflows/test.yml
  noxfile.py
  pyproject.toml
Labels: maintenance

#400 gh-399: hide `kappa_ia_nla`
  glass/__init__.py
  glass/galaxies.py
Labels: bug

#372 gh-272: add tests for glass.points
  tests/test_points.py
Labels: maintenance

#381 gh-188: add docstrings to all functions and tidy docs
  docs/conf.py
  glass/core/algorithm.py
  glass/core/array.py
  glass/ext/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
Labels: documentation, enhancement, science

#420 gh-419: fix imports
  glass/ext/__init__.py
  glass/fields.py
  glass/shells.py
  tests/test_points.py
Labels: bug

#416 gh-286: replace `stable` in docs with tag for `sdist`
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.md
  docs/manual/first-steps.rst
  pyproject.toml
Labels: documentation, enhancement, releases

#428 gh-418: add variable names for `Yields` vars
  glass/fields.py
  glass/points.py
  glass/user.py
Labels: bug, documentation

#426 gh-390: release 2024.2
  CHANGELOG.md
  CONTRIBUTING.md
  docs/manual/releases.rst
Labels: releases

#429 gh-430: fix for release action
  .github/workflows/release.yml
Labels: releases

#391 gh-163: drop `Python 3.9` & `NumPy < 2.1.1` support
  .github/workflows/test.yml
  examples/1-basic/photoz.ipynb
  glass/core/array.py
  glass/fields.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shells.py
  noxfile.py
  pyproject.toml
  tests/test_lensing.py
  tests/test_shells.py
Labels: enhancement, infrastructure, dependencies, blocked

#435 Fix linting
  .github/workflows/release.yml
Labels: bug

#392 gh-384: rename all internal functions to `trapezoid` over `trapz`
  glass/core/array.py
  glass/galaxies.py
  glass/observations.py
  glass/points.py
  tests/core/test_array.py
Labels: api

#444 gh-443: `if` should be `elif` in `fixed_zbins`
  glass/observations.py
Labels: bug, testing

#446 gh-445: place all public function in `__all__`
  glass/__init__.py
Labels: bug

#442 gh-441: import directly from `glass` in tests
  tests/conftest.py
  tests/test_fields.py
  tests/test_fits.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_points.py
  tests/test_shapes.py
  tests/test_shells.py
Labels: bug, testing

#448 gh-447: make sure `dz` gives the same results as `nbins`
  glass/observations.py
Labels: bug

#451 gh-450: move all `pytest.fixture` into `conftest.py`
  tests/conftest.py
  tests/test_lensing.py
Labels: enhancement, testing

#455 gh-453: don't run PR title checker on dependabot PRs
  .github/workflows/pull_request.yml
Labels: infrastructure

#457 gh-456: call `redshift_grid` within `distance_grid`
  glass/shells.py
Labels: enhancement

#436 gh-271: add tests for `glass.observations`
  glass/observations.py
  tests/test_observations.py
Labels: enhancement, infrastructure, testing

#374 gh-269: add tests for glass.fields
  tests/test_fields.py
Labels: maintenance, testing

#422 gh-274: add missing tests for `glass.user`
  tests/test_user.py
Labels: testing

#395 gh-368: add type overloading for `lensing.from_convergence`
  glass/lensing.py
Labels: enhancement, infrastructure

#427 gh-421: fix TestPyPI deployment
  .github/workflows/release.yml
Labels: bug, infrastructure

#425 gh-398: consistent plotting for notebooks
  .matplotlibrc
  examples/1-basic/matplotlibrc
  examples/2-advanced/matplotlibrc
Labels: documentation, enhancement, science

#461 gh-460: update notebooks inplace when running nox -s examples
  noxfile.py
Labels: bug, infrastructure

#462 gh-440: remove scipy as a test dependency
  .github/test-constraints.txt
  pyproject.toml
  tests/core/test_algorithm.py
  tests/core/test_array.py
Labels: dependencies, testing
