Repository glass-dev/glass, pull requests merged in 2024-09, with the labels that each got.

#197 gh-183: expand list of classifiers
  pyproject.toml
Labels: enhancement, infrastructure

#192 gh-181: fix references to English version of the docs
  README.md
  pyproject.toml
Labels: bug, documentation

#191 gh-182: fix citation link on PyPI
  README.md
Labels: bug, documentation, science

#190 gh-206: tidy up and apply `toml-sort` to `pyproject.toml`
  .pre-commit-config.yaml
  pyproject.toml
Labels: enhancement, maintenance

#194 gh-184: Change copyright range in documentation to be automated
  .gitignore
  LICENSE
  docs/conf.py
Labels: documentation, enhancement

#215 gh-175: update and rename CITATION.md to CITATION.bib
  CITATION.bib
Labels: documentation, maintenance

#212 gh-211: cancel intermediate builds
  .github/workflows/test.yml
Labels: infrastructure

#205 gh-203: remove PR review action
  .github/workflows/pull_request_review.yml
Labels: infrastructure

#217 gh-173: move core tests out of the SDist
  tests/core/__init__.py
  tests/core/test_algorithm.py
  tests/core/test_array.py
Labels: maintenance

#213 gh-46: add infrastructure for coveralls (coverage)
  .github/workflows/test.yml
  .gitignore
  README.md
  pyproject.toml
Labels: infrastructure

#218 gh-200: update CONTRIBUTING.md to follow new title convention
  CONTRIBUTING.md
Labels: documentation

#220 gh-84: enable doctests using pytest-doctestplus
  .github/workflows/test.yml
  .gitignore
  pyproject.toml
Labels: infrastructure

#223 Don't make second box mandatory for feature request
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: documentation, infrastructure

#199 STY: add `ruff-format` and remove `flake8`
  .flake8
  .git-blame-ignore-revs
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/conf.py
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/photoz.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/core/__init__.py
  glass/core/algorithm.py
  glass/core/array.py
  glass/core/constants.py
  glass/ext/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
  tests/core/test_array.py
  tests/test_fields.py
  tests/test_fits.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_points.py
  tests/test_shapes.py
  tests/test_shells.py
Labels: maintenance

#227 gh-226: run `prettier` over the repo via a `pre-commit` hook
  .git-blame-ignore-revs
  .github/pr-title-checker-config.json
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: infrastructure

#229 Fix typos running `crate-ci/typos` over code base
  CODE_OF_CONDUCT.md
  glass/shells.py
  glass/user.py
Labels: bug

#236 gh-170: add traditional pygrep hooks
  .pre-commit-config.yaml
  docs/examples.rst
  docs/manual/releases.rst
Labels: infrastructure

#235 gh-170: add traditional pre-commit-hooks
  .github/test-constraints.txt
  .pre-commit-config.yaml
Labels: infrastructure

#237 gh-204: split examples job and run it only on code changes
  .github/workflows/examples.yml
  .github/workflows/test.yml
Labels: infrastructure, maintenance

#209 gh-176: revamp publishing workflow
  .github/workflows/release.yml
Labels: infrastructure

#244 gh-222: add infrastructure for testpypi uploads
  .github/workflows/release.yml
Labels: infrastructure

#221 gh-107: add all public functions/classes under glass namespace
  docs/user/how-glass-works.rst
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/photoz.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
Labels: maintenance

#245 gh-234: add pre-commit.ci support
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  docs/make.bat
Labels: infrastructure

#242 gh-204: examples run twice on PRs
  .github/workflows/examples.yml
  .github/workflows/test.yml
Labels: infrastructure

#247 gh-226: pre-commit's mirror of prettier is obsolete
  .pre-commit-config.yaml
Labels: maintenance

#232 gh-231: add `ruff` linting to `pre-commit`
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  docs/conf.py
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/photoz.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/__init__.py
  glass/core/__init__.py
  glass/core/algorithm.py
  glass/core/array.py
  glass/core/constants.py
  glass/ext/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
  tests/core/test_algorithm.py
  tests/core/test_array.py
  tests/test_fits.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_points.py
  tests/test_shells.py
Labels: enhancement, infrastructure

#254 gh-233: don't run workflows on draft PRs
  .github/workflows/examples.yml
  .github/workflows/test.yml
Labels: infrastructure

#230 gh-170: add `yamllint` and run over the repo
  .github/dependabot.yml
  .github/workflows/examples.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .readthedocs.yml
Labels: infrastructure

#241 gh-208: remove legacy random number generation
  tests/conftest.py
  tests/core/test_algorithm.py
  tests/test_lensing.py
  tests/test_points.py
Labels: maintenance

#251 gh-180: add badges for pre-commit, python versions, discussion, license
  README.md
Labels: documentation, maintenance

#261 gh-260: remove glass.core.constants
  examples/1-basic/photoz.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  glass/core/constants.py
  glass/points.py
Labels: maintenance

#253 gh-238: utilise tmp_path correctly in tests
  .gitignore
  tests/test_fits.py
Labels: maintenance

#252 gh-240: remove old file headers (license and author)
  glass/core/__init__.py
  glass/core/algorithm.py
  glass/core/array.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
Labels: maintenance

#250 gh-170: add scientific python recommended blacken-docs
  .pre-commit-config.yaml
Labels: documentation, infrastructure

#281 gh-267: move verbose output flag for ruff and pytest to pyproject.toml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#279 gh-278: ignore reduandant lines and files from coverage report
  pyproject.toml
Labels: infrastructure

#255 gh-185: update CONTRIBUTING.md (developer guide)
  CONTRIBUTING.md
Labels: documentation

#258 gh-257: use pytest-mock instead of unittest.mock
  pyproject.toml
  tests/test_galaxies.py
Labels: maintenance

#289 gh-288: run CI when a draft PR is marked as ready
  .github/workflows/examples.yml
  .github/workflows/test.yml
Labels: bug
