Repository glass-dev/glass, pull requests merged in 2025-05, with the labels that each got.

#617 gh-616: use `position_weights()` in galaxy redshift example
  examples/1-basic/galaxy-redshift-distributions.ipynb
Labels: documentation, enhancement

#619 gh-611: xp fixture for array API tests
  CONTRIBUTING.md
  tests/conftest.py
Labels: array-api, testing

#537 gh-124: use `cosmology.api` over the `cosmology` package
  examples/1-basic/density.ipynb
  examples/1-basic/galaxy-redshift-distributions.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/cosmology.py
  glass/galaxies.py
  glass/lensing.py
  glass/shells.py
  pyproject.toml
  tests/conftest.py
  tests/test_lensing.py
  tests/test_shells.py
Labels: enhancement, typing, dependencies, science

#622 gh-402: wrap NumPy RNGs to return array_api_strict Array
  glass/_array_api_utils.py
  glass/jax.py
  pyproject.toml
  tests/conftest.py
  tests/test_array_api_utils.py
  tests/test_jax.py
Labels: enhancement, array-api

#595 gh-519: test array API compliance of legacy mode functions
  glass/algorithm.py
  tests/test_algorithm.py
Labels: array-api, testing

#626 gh-594: split PyPI and TestPyPI deployments
  .github/workflows/release.yml
Labels: infrastructure, maintenance
