Repository glass-dev/glass, pull requests merged in 2025-01, with the labels that each got.

#474 gh-469: @pre-commit.ci shouldn't break title checking
  .github/workflows/pull_request.yml
Labels: bug, infrastructure

#484 Manual revert of #467
  glass/core/array.py
  glass/points.py
  glass/shells.py
Labels: bug

#471 gh-468: fix virtualenv in testing
  .github/workflows/test.yml
  noxfile.py
Labels: bug, testing

#459 gh-439: infrastructure for testing array API compatibility
  .github/workflows/test.yml
  CONTRIBUTING.md
  noxfile.py
  tests/conftest.py
Labels: array-api, testing

#463 gh-424: add a simple PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, infrastructure

#454 gh-275: add tests for `glass.lensing`
  tests/test_lensing.py
  tests/test_observations.py
  tests/test_points.py
Labels: enhancement, testing

#449 gh-273: add tests for `glass.shells`
  tests/conftest.py
  tests/test_shells.py
Labels: enhancement, testing
