Repository glass-dev/glass, pull requests merged in 2025-03, with the labels that each got.

#548 gh-547: comment out CHANGELOG entry by default
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#563 gh-554: move contributors to a file and show in docs
  .all-contributorsrc
  README.md
  docs/CONTRIBUTORS.md
  docs/conf.py
  docs/index.rst
  pyproject.toml
Labels: documentation, enhancement, infrastructure

#579 gh-578: mutable argument should be empty list rather than `None`
  examples/2-advanced/legacy-mode.ipynb
Labels: bug

#565 gh-552: add docs on all-contributors
  CONTRIBUTING.md
Labels: documentation

#574 gh-573: add keyword `rng` to functions in notebooks
  examples/2-advanced/legacy-mode.ipynb
Labels: bug, documentation

#584 gh-583: fix flakiness of `test_generate`
  .github/workflows/test.yml
  tests/test_fields.py
Labels: maintenance

#586 gh-585: remove redunant `glass.ext.camb` import
  examples/2-advanced/legacy-mode.ipynb
Labels: bug

#582 gh-571: add a 20 min timeout to example runs
  .github/workflows/examples.yml
Labels: infrastructure

#581 gh-580: examples should run in the CI if they are modified
  .github/workflows/examples.yml
Labels: bug, infrastructure

#576 gh-572: make `multalm` private
  glass/__init__.py
  glass/fields.py
  tests/test_fields.py
Labels: maintenance, api

#533 gh-487: reorder alms in _generate_grf to glass ordering
  glass/fields.py
  tests/test_fields.py
Labels: api

#588 gh-587: run examples if a PR is labeled 'run-examples'
  .github/workflows/run-examples.yml
  .github/workflows/test-examples-on-label.yml
  .github/workflows/test-examples-on-push.yml
Labels: infrastructure, maintenance, run-examples

#589 gh-568: convert `_weight` funcs to classes for `_windows` funcs
  glass/__init__.py
  glass/shells.py
  tests/test_shells.py
Labels: enhancement, infrastructure
