Repository glass-dev/glass, pull requests merged in 2025-02, with the labels that each got.

#510 gh-499: rm D205, D401, EM101, EM102, TRY003
  glass/core/__init__.py
  glass/fields.py
  glass/galaxies.py
  glass/grf/_core.py
  glass/grf/_transformations.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
Labels: maintenance

#511 gh-491: use try-except for __version__
  glass/__init__.py
Labels: maintenance

#507 gh-503: move all typing related imports into `from`
  glass/core/algorithm.py
  glass/core/array.py
  glass/fields.py
  glass/galaxies.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shapes.py
  glass/shells.py
  glass/user.py
  pyproject.toml
  tests/conftest.py
  tests/core/test_array.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_points.py
  tests/test_user.py
Labels: typing

#512 gh-501: change imports to be directly from `glass`
  docs/user/how-glass-works.rst
  glass/fields.py
  glass/galaxies.py
  glass/grf/_solver.py
  glass/grf/_transformations.py
  glass/lensing.py
  glass/observations.py
  glass/points.py
  glass/shells.py
  pyproject.toml
  tests/conftest.py
  tests/core/test_algorithm.py
  tests/core/test_array.py
  tests/test_fields.py
  tests/test_galaxies.py
  tests/test_lensing.py
  tests/test_observations.py
  tests/test_points.py
  tests/test_shapes.py
  tests/test_shells.py
  tests/test_user.py
Labels: maintenance

#516 gh-515: fix coveralls
  .github/workflows/test.yml
Labels: bug, infrastructure

#517 gh-501: changes missed in #507
  glass/core/array.py
  pyproject.toml
Labels: typing

#520 gh-501: move custom types into `TYPE_CHECKING`
  glass/grf/_core.py
  glass/shells.py
Labels: typing

#521 gh-480: fix union1d typing error
  .pre-commit-config.yaml
  glass/shells.py
Labels: maintenance

#497 gh-496: functions for legacy mode
  .gitignore
  docs/conf.py
  docs/examples.rst
  docs/reference/fields.rst
  examples/2-advanced/legacy-mode.ipynb
  glass/__init__.py
  glass/core/algorithm.py
  glass/fields.py
  pyproject.toml
  tests/core/test_algorithm.py
  tests/test_fields.py
Labels: api

#514 gh-513: make algorithm a public module
  docs/modules/algorithm.rst
  docs/modules/index.rst
  docs/reference/fields.rst
  glass/__init__.py
  glass/algorithm.py
  glass/fields.py
  glass/shells.py
  tests/test_algorithm.py
  tests/test_fields.py
Labels: maintenance, api

#518 gh-508: create standalone bibliography page
  docs/user/bibliography.rst
  docs/user/how-glass-works.rst
  docs/user/index.rst
  glass/algorithm.py
  glass/galaxies.py
  glass/grf/_transformations.py
  glass/lensing.py
  glass/observations.py
  glass/shapes.py
Labels: documentation

#524 gh-478: glass.core.array -> glass.arraytools
  glass/arraytools.py
  glass/core/__init__.py
  glass/galaxies.py
  glass/observations.py
  glass/points.py
  glass/shells.py
  tests/core/__init__.py
  tests/test_arraytools.py
Labels: maintenance, api

#523 gh-504: deprecate old generator functions
  examples/1-basic/density.ipynb
  examples/1-basic/lensing.ipynb
  examples/1-basic/matter.ipynb
  examples/1-basic/photoz.ipynb
  examples/1-basic/shells.ipynb
  examples/2-advanced/cosmic_shear.ipynb
  examples/2-advanced/legacy-mode.ipynb
  examples/2-advanced/stage_4_galaxies.ipynb
  glass/__init__.py
  glass/fields.py
  pyproject.toml
  tests/test_fields.py
Labels: maintenance, api

#528 gh-509: new inv_triangle_number popped up in another PR
  glass/fields.py
Labels: bug, maintenance

#529 Change the pre-commit updates to be monthly
  .pre-commit-config.yaml
Labels: infrastructure

#531 gh-532: prepare for the `v2025.1` release
  CHANGELOG.md
  docs/manual/releases.rst
Labels: documentation, releases

#541 gh-540: add all contributors config
  .all-contributorsrc.json
  README.md
Labels: documentation, enhancement, science

#543 Rename .all-contributorsrc.json to .all-contributorsrc
  .all-contributorsrc
Labels: bug
