Repository glass-dev/glass, pull requests merged in 2025-04, with the labels that each got.

#593 gh-592: use `--doctest-plus-generate-diff=overwrite`
  noxfile.py
Labels: infrastructure

#603 gh-602: pin python version and numpy for pre-commit
  .pre-commit-config.yaml
  glass/fields.py
Labels: bug, infrastructure

#600 gh-599: swap all `xp` vars to `xq` (and similar)
  glass/algorithm.py
  glass/arraytools.py
  tests/test_arraytools.py
Labels: array-api

#604 gh-601: add a utility function to fetch array namespace
  .pre-commit-config.yaml
  glass/_array_api_utils.py
  pyproject.toml
  tests/test_array_api_utils.py
Labels: maintenance
